fintrack/urls.py
from django.contrib import admin
from django.urls import path, include
from tracker import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tracker.urls')),
    path('users/', include('users.urls', namespace="users")),
]

tracker/urls.py
from django.urls import path, include, re_path, register_converter
from . import views

# app_name = 'tracker'

urlpatterns = [
    path('', views.TrackerHome.as_view(), name='home'),
    path('operations/', views.AllOperations.as_view(), name='all_operations'),
    path('incomes/', views.Incomes.as_view(), name='incomes'),
    path('expenses/', views.Expenses.as_view(), name='expenses'),
    path('visual-report/', views.visual_report, name='visual_report'),
    # path('feedback/', views.feedback, name='feedback'),
    path('create-operation/', views.CreateOperation.as_view(), name='create_operation'),
    path('create-category/', views.CreateCategory.as_view(), name='create_category'),
    path('delete-cat/<slug:slug>/', views.DeleteCategory.as_view(), name='delete_category'),
    path('delete-op/<slug:slug>/', views.DeleteOperation.as_view(), name='delete_operation'),
    path('edit-cat/<slug:slug>/', views.UpdateCategory.as_view(), name='update_category'),
    path('edit-op/<slug:slug>/', views.UpdateOperation.as_view(), name='update_operation'),
]

users/urls.py
from . import views
from django.urls import path, reverse_lazy
from django.contrib.auth.views import (LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView,
                                       PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView)

app_name = 'users'

urlpatterns =[
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),
    path('password-reset/',
         PasswordResetView.as_view(
             template_name='users/password_reset_form.html',
             email_template_name='users/password_reset_email.html',
             success_url=reverse_lazy('users:password_reset_done')
         ),
         name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name = "users/password_reset_done.html"),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url=reverse_lazy('users:password_reset_complete')),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html',),
         name='password_reset_complete'),
    path('feedback/', views.FeedbackCreateView.as_view(), name='feedback')
    ]

tracker/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Operation(models.Model):
    class TypeOfMethod(models.IntegerChoices):
        CARD = 0, "Банковская карта"
        CASH = 1, "Наличные"
        QR = 2, "QR-код"
        SBP = 3, "СБП перевод"

    class TransactionType(models.IntegerChoices):
        EXPENSE = 0, "Расход"
        INCOME = 1, "Доход"

    name = models.CharField(max_length=255, verbose_name='Название операции')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='Слаг')
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    time_update = models.DateTimeField(auto_now=True, verbose_name='Время изменения')
    amount = models.FloatField(blank=False, verbose_name='Сумма')
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True, verbose_name='Категория', related_name="operations")
    method = models.PositiveSmallIntegerField(choices=TypeOfMethod.choices, default=TypeOfMethod.CARD, verbose_name='Метод оплаты')
    type = models.PositiveSmallIntegerField(choices=TransactionType.choices, default=TransactionType.EXPENSE, verbose_name='Тип операции')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('home')


# модель категорий
class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name='Название категории')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='Слаг')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь',)

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse('home')


class ContextMenu(models.Model):
    title = models.CharField(max_length=100, verbose_name="Название")
    url_name = models.CharField(max_length=100, verbose_name="Url")
    order = models.IntegerField(null=True, blank=True, verbose_name='sort_order', default=1)

    def __str__(self):
        return self.title

tracker/views.py
from django.shortcuts import render
from django.views.generic import ListView
from tracker.models import Operation, Category
from django.http import HttpResponse
from django.views.generic import CreateView, DeleteView, UpdateView, TemplateView
from slugify import slugify
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .mixins import TrackerMixin, CategoriesMixin
from django.contrib.auth.decorators import login_required


class TrackerHome(TrackerMixin, TemplateView):
    template_name = 'base.html'


class CreateOperation(LoginRequiredMixin, TrackerMixin, CategoriesMixin, CreateView):
    model = Operation
    fields = ['name', 'amount', 'method', 'type', 'category']
    title_page = 'Добавление операции'
    template_name = 'tracker/create.html'
    extra_context = {'title': 'Создание Операции'}

    def form_valid(self, form):
        obj = form.save(commit=False)
        base_slug = slugify(obj.name)
        count = Operation.objects.filter(slug__startswith=base_slug).count()
        obj.slug = f"{base_slug}{count + 1}" if count else base_slug
        obj.user = self.request.user
        return super().form_valid(form)


    # def get_form(self, form_class=None):
    #     form = super().get_form(form_class)
    #     user = self.request.user
    #     form.fields['category'].queryset = Category.objects.filter(user=user)
    #
    #     return form


class CreateCategory(LoginRequiredMixin, TrackerMixin, CreateView):
    model = Category
    fields = ['name']
    template_name = 'tracker/create.html'
    extra_context = {'title': 'Создание категории'}

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['categories'] = Category.objects.all()
    #     return context

    def form_valid(self, form):
        obj = form.save(commit=False)
        base_slug = slugify(obj.name)
        count = Category.objects.filter(slug__startswith=base_slug).count()
        obj.slug = f"{base_slug}{count + 1}" if count else base_slug
        obj.user_id = self.request.user.id
        return super().form_valid(form)


class DeleteCategory(LoginRequiredMixin, TrackerMixin, DeleteView):
    model = Category
    template_name = 'tracker/delete.html'
    success_url = reverse_lazy('home')
    extra_context = {'title': 'Удаление категории'}

    def get_queryset(self):
        return Category.objects.filter(user=self.request.user)

    def delete(self, request, *args, **kwargs):
        response = super().delete(request, *args, **kwargs)
        return response


class DeleteOperation(LoginRequiredMixin, DeleteView):
    model = Operation
    template_name = 'tracker/delete.html'
    success_url = reverse_lazy('home')
    extra_context = {'title': 'Удаление операции'}

    def get_queryset(self):
        return Operation.objects.filter(user=self.request.user)



    def delete(self, request, *args, **kwargs):
        response = super().delete(request, *args, **kwargs)
        return response


class UpdateCategory(LoginRequiredMixin, TrackerMixin,  UpdateView):
    model = Category
    fields = ['name']
    template_name = 'tracker/update.html'
    success_url = reverse_lazy('home')

    def get_queryset(self):
        return Category.objects.filter(user=self.request.user)

    def form_valid(self, form):
        obj = form.save(commit=False)
        base_slug = slugify(obj.name)
        count = Category.objects.filter(slug__startswith=base_slug).count()
        obj.slug = f"{base_slug}{count + 1}" if count else base_slug
        return super().form_valid(form)


class UpdateOperation(LoginRequiredMixin, TrackerMixin, CategoriesMixin,  UpdateView):
    model = Operation
    fields = ['name', 'amount', 'method', 'type', 'category']
    template_name = 'tracker/update.html'
    success_url = reverse_lazy('home')

    def get_queryset(self):
        return Operation.objects.filter(user=self.request.user)

    def form_valid(self, form):
        obj = form.save(commit=False)
        base_slug = slugify(obj.name)
        count = Operation.objects.filter(slug__startswith=base_slug).count()
        obj.slug = f"{base_slug}{count + 1}" if count else base_slug
        return super().form_valid(form)


class AllOperations(LoginRequiredMixin, TrackerMixin, ListView):
    template_name = 'tracker/index.html'
    context_object_name = 'operations'

    def get_queryset(self):
        return Operation.objects.filter(user_id=self.request.user.id)
        # return Operation.objects.all().values('name', 'amount', 'type', 'category')





class Incomes(LoginRequiredMixin, TrackerMixin, ListView):
    template_name = 'tracker/index.html'
    context_object_name = 'operations'
    extra_context = {'view': 'incomes'}
    def get_queryset(self):
        return Operation.objects.filter(type=1, user_id=self.request.user.id) # 1 = доход

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['view'] = 'incomes'
    #     context['categories'] = Category.objects.all()
    #     return context


class Expenses(LoginRequiredMixin, TrackerMixin, ListView):
    template_name = 'tracker/index.html'
    context_object_name = 'operations'
    extra_context = {'view': 'expenses'}

    def get_queryset(self):
        return Operation.objects.filter(type=0, user_id=self.request.user.id) # 1 = доход




@login_required
def visual_report(request):
    op_type = request.GET.get('type', 'expense')
    chart_type = request.GET.get('chart', 'bar')

    if op_type == 'income':
        type_value = Operation.TransactionType.INCOME
        op_type_label = "Доходы"
    else:
        type_value = Operation.TransactionType.EXPENSE
        op_type_label = "Расходы"

    operations = Operation.objects.filter(user=request.user, type=type_value)

    data = {}
    for op in operations:
        cat_name = op.category.name if op.category else "Без категории"
        data[cat_name] = data.get(cat_name, 0) + op.amount

    labels = list(data.keys())
    values = list(data.values())

    return render(request, 'tracker/visual_report.html', {
        'labels': labels,
        'values': values,
        'title': "Отчет по операциям",
        'op_type_label': op_type_label,
        'chart_type': chart_type
    })

tracker/templates/tracker/create.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block content %}
{{ title }}
<form action="" method="POST" class="form-label">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
        {{ form.as_p }}
    <input type="submit" value="Добавить">
</form>
{% endblock %}

tracker/templates/tracker/createoperation.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block content %}
{{ title }}
<form action="" method="POST" >
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

tracker/templates/tracker/delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Удаление записи</h1>
<form action="" method="POST">
    {% csrf_token %}
    <p>Вы уверены, что хотите удалить запись "{{ object }}"?</p>
    {{form}}
    <p><button type="submit">Удалить</button></p>
</form>
{% endblock %}

tracker/templates/tracker/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
<html>
<body>
    {% block content %}

    <div class="table-container">
        <table border="3" class="operations-table">
            <caption>
                {% if view == "all" %}
                    <h3>Все операции пользователя</h3>
                {% elif view == "incomes" %}
                    <h3>Все доходы пользователя</h3>
                {% elif view == "expenses" %}
                    <h3>Все расходы пользователя</h3>
                {% endif %}
            </caption>
            <thead>
                <tr>
                    <th>Название</th>
                    <th>Сумма</th>
                    <th>Категория</th>
                    <th>Метод оплаты</th>
                    <th>Тип операции</th>
                    <th>Изменить запись</th>
                    <th>Удалить запись</th>
                </tr>
            </thead>
            <tbody>
                {% for operation in operations %}
                <tr>
                    <td>{{ operation.name }}</td>
                    <td>{{ operation.amount }} руб.</td>
                    <td>{{ operation.category.name }}</td>
                    <td>{{ operation.get_method_display }}</td>
                    <td>{{ operation.get_type_display }}</td>
                    <td><button type="button"><a href="{% url 'update_operation' operation.slug %}">Изменить</a></button></td>
                    <td><button type="button"><a href="{% url 'delete_operation' operation.slug %}">Удалить</a></button></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% endblock %}
</body>
</html>

tracker/templates/tracker/update.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block content %}
{{ title }}
<form action="" method="POST" >
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {{ form.as_p }}
    <input type="submit" value="Обновить">
</form>
{% endblock %}

tracker/templates/tracker/visual_report.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ title }}</h1>

<form method="get" action="{% url 'visual_report' %}">
    <label for="type">Тип операции:</label>
    <select name="type" id="type">
        <option value="expense" {% if request.GET.type == "expense" or not request.GET.type %}selected{% endif %}>Расходы</option>
        <option value="income" {% if request.GET.type == "income" %}selected{% endif %}>Доходы</option>
    </select>

    <label for="chart">Тип графика:</label>
    <select name="chart" id="chart">
        <option value="bar" {% if request.GET.chart == "bar" or not request.GET.chart %}selected{% endif %}>Столбчатая</option>
        <option value="pie" {% if request.GET.chart == "pie" %}selected{% endif %}>Круговая</option>
    </select>

    <button type="submit">Построить</button>
</form>


<canvas id="myChart" width="400" height="200"></canvas>

<!-- Подключение Chart.js -->
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    const labels = {{ labels|safe }};
    const values = {{ values|safe }};
    const chartType = "{{ chart_type|default:'bar' }}";  // Тип из Django

    const ctx = document.getElementById('myChart').getContext('2d');
    new Chart(ctx, {
        type: chartType,  // используем динамический тип
        data: {
            labels: labels,
            datasets: [{
                label: '{{ op_type_label|default:"Значения" }}',
                data: values,
                backgroundColor: [
                    'rgba(255, 99, 132, 0.6)',
                    'rgba(54, 162, 235, 0.6)',
                    'rgba(255, 206, 86, 0.6)',
                    'rgba(75, 192, 192, 0.6)',
                    'rgba(153, 102, 255, 0.6)',
                    'rgba(255, 159, 64, 0.6)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            responsive: true,
            plugins: {
                legend: {
                    display: chartType === 'pie' || chartType === 'doughnut' // в столбчатых можно отключить
                }
            },
            scales: chartType === 'bar' || chartType === 'line' ? {
                y: { beginAtZero: true }
            } : {}
        }
    });
</script>

{% endblock %}