fintrack/urls.py
from django.contrib import admin
from django.urls import path, include
from tracker import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tracker.urls')),
    path('users/', include('users.urls', namespace="users")),
]

users/urls.py
from . import views
from django.urls import path, reverse_lazy
from django.contrib.auth.views import (LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView,
                                       PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView)

app_name = 'users'

urlpatterns =[
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),
    path('password-reset/',
         PasswordResetView.as_view(
             template_name='users/password_reset_form.html',
             email_template_name='users/password_reset_email.html',
             success_url=reverse_lazy('users:password_reset_done')
         ),
         name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name = "users/password_reset_done.html"),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url=reverse_lazy('users:password_reset_complete')),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html',),
         name='password_reset_complete'),
    path('feedback/', views.FeedbackCreateView.as_view(), name='feedback')
    ]

users/models.py
from django.db import models
from django.contrib.auth.models import User


class Feedback(models.Model):
    subject = models.CharField(max_length=255, verbose_name='Тема письма')
    email = models.EmailField(max_length=255, verbose_name='Электронный адрес (email)')
    content = models.TextField(verbose_name='Содержимое письма')
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')
    ip_address = models.GenericIPAddressField(verbose_name='IP отправителя', blank=True, null=True)
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        verbose_name = 'Обратная связь'
        verbose_name_plural = 'Обратная связь'
        ordering = ['-time_create']
        db_table = 'tracker_user_feedback'


    def __str__(self):
        return f'Письмо от {self.email}'

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import get_user_model
from django.contrib.auth.views import LogoutView, PasswordChangeForm
from .models import Feedback
from django_recaptcha.fields import ReCaptchaField
from django_recaptcha.widgets import ReCaptchaV2Checkbox
from fintrack import settings


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label="Пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label="Логин", widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label="Пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label="Повтор пароля", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox, public_key=settings.RECAPTCHA_PUBLIC_KEY,
                               private_key=settings.RECAPTCHA_PRIVATE_KEY, label='ReCAPTCHA')

    class Meta:
        model = get_user_model()
        fields = ['username', 'email',  'password1', 'password2']
        labels = {
            'email': 'E-mail',
            # 'first_name': 'Имя',
            # 'last_name': 'Фамилия',
        }
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-input'}),
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Такой E-mail уже существует!")
        return email


class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.CharField(disabled=True, required=False, label='E-mail', widget=forms.TextInput(attrs={'class': 'form-input'}))


    class Meta:
        model = get_user_model()
        fields = ['username', 'email','first_name', 'last_name']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }



class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Старый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(label="Новый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label="Подтверждение пароля",
                                    widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox, public_key=settings.RECAPTCHA_PUBLIC_KEY,
                               private_key=settings.RECAPTCHA_PRIVATE_KEY, label='ReCAPTCHA')


class FeedbackCreateForm(forms.ModelForm):

    class Meta:
        model = Feedback
        fields = ('subject', 'email', 'content')

        widgets = {
            'subject': forms.TextInput(attrs={'class': 'form-input'}),
            'email': forms.TextInput(attrs={'class': 'form-input'}),
            'content': forms.TextInput(attrs={'class': 'form-input'}),
        }

users/views.py
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView
from .forms import RegisterUserForm, LoginUserForm, ProfileUserForm, UserPasswordChangeForm, FeedbackCreateForm
from django.urls import reverse_lazy
from django.contrib.auth.views import LogoutView, PasswordChangeView, LoginView, PasswordChangeDoneView
from django.contrib.auth import get_user_model
from django.contrib.messages.views import SuccessMessageMixin
from .emails import send_contact_email_message
from .utils import get_client_ip
from .models import Feedback
from django.contrib.auth.mixins import LoginRequiredMixin


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Авторизация'}

    def get_success_url(self):
        return reverse_lazy('home')


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    extra_context = {'title': "Регистрация"}
    success_url = reverse_lazy('users:login')


class ProfileUser(UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {'title': 'Профиль пользователя'}

    def get_success_url(self):
        return reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordChange(PasswordChangeView):
    form_class = UserPasswordChangeForm
    template_name = 'users/password_change_form.html'
    # success_url = reverse_lazy("users:profile")
    success_url = reverse_lazy("users:password_change_done")


class FeedbackCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Feedback
    form_class = FeedbackCreateForm
    success_message = "Ваше письмо успешно отправлено администрации сайта"
    template_name = "users/feedback.html"
    extra_context = {'title': "Контактная форма"}
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        if form.is_valid():
            feedback = form.save(commit=False)
            feedback.ip_address = get_client_ip(self.request)
            if self.request.user.is_authenticated:
                feedback.user = self.request.user
            send_contact_email_message(feedback.subject, feedback.email,
                                       feedback.content, feedback.ip_address, feedback.user_id)
        return super().form_valid(form)

users/templates/users/feedback.html
{% extends 'base.html' %}
{% block content %}
    <h4>Контактная форма</h4>
    <form method="post" action="{% url 'users:feedback' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="d-grid gap-2 d-md-block mt-2">
            <button type="submit" class="btn btn-dark">Отправить письмо</button>
        </div>
    </form>
{% endblock %}

users/templates/users/feedback_email_send.html
{% autoescape off %}

Здравствуйте, Администратор,

С контактной формы поступило новое сообщение со следующим содержимым:

    {{ content }}

    IP Адрес отправителя: {{ ip }}
    Email отправителя: {{ email }}
    {% if user %}Пользователь: {{ user.username }}{% endif %}

Команда сайта Fintrack

{% endautoescape %}

users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
<h1>Авторизация</h1>

<form action="" method="POST">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
        <div class="form-row">
            <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>
            {{ f }}
        </div>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">Войти</button></p>
</form>

<p><a href="{% url 'users:password_reset' %}">Забыли пароль?</a></p>


{% endblock %}

users/templates/users/password_change_done.html
{% extends 'base.html' %}

{% block content %}
<h1>Пароль успешно изменен!</h1>

<p>Вы успешно изменили пароль. <a href="{% url 'users:profile' %}">Вернуться в профиль.</a></p>
{% endblock %}

users/templates/users/password_change_form.html
{% extends 'base.html' %}

{% block content %}
<h1>Изменение пароля</h1>

<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
            {% if f.label == "ReCAPTCHA" %}
                    <p><label class="form-label" for="{{ f.id_for_label }}"></label> {{ f }}</p>
            {% else %}
                <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}: </label> {{ f }}</p>
            {% endif %}
    {% endfor %}

    <p><button type="submit">Изменить пароль</button></p>
</form>

{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
<h1>Пароль изменен</h1>

<p>Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для
  <a href="{% url 'users:login' %}">входа в систему</a>.</p>

{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
<h1>Новый пароль</h1>

<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p><button type="submit">Сохранить</button></p>
</form>

{% endblock %}

users/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h1>Сброс пароля</h1>

<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
<h1>Восстановление пароля</h1>

<form method="post">
    {% csrf_token %}
{% for f in form %}
<p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
<div class="form-error">{{ f.errors }}</div>
{% endfor %}

    <p><button type="submit">Сбросить по E-mail</button></p>
</form>

{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
 
{% block content %}
<h1>Профиль</h1>
 
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
 
    <p ><button type="submit">Сохранить</button></p>
</form>

<hr>
<p ><a href="{% url 'users:password_change' %}">Сменить пароль</a></p>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
    {% csrf_token %}
<input type="hidden" name="next" value="{{ next }}" />
    {% for f in form %}
        <div class="form-row">
            {% if f.label == "ReCAPTCHA" %}
                    <p><label class="form-label" for="{{ f.id_for_label }}"></label> {{ f }}</p>
            {% else %}
                <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}: </label> {{ f }}</p>
            {% endif %}
    </div>
            <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p ><button type="submit">Зарегистрироваться</button></p>
</form>

{% endblock %}