fintrack/urls.py
from django.contrib import admin
from django.urls import path, include
from tracker import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tracker.urls')),
    path('users/', include('users.urls', namespace="users")),
]

users/urls.py
from . import views
from django.urls import path, reverse_lazy
from django.contrib.auth.views import (LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView,
                                       PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView)

app_name = 'users'

urlpatterns =[
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),
    path('password-reset/',
         PasswordResetView.as_view(
             template_name='users/password_reset_form.html',
             email_template_name='users/password_reset_email.html',
             success_url=reverse_lazy('users:password_reset_done')
         ),
         name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name = "users/password_reset_done.html"),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url=reverse_lazy('users:password_reset_complete')),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html',),
         name='password_reset_complete'),
    path('feedback/', views.FeedbackCreateView.as_view(), name='feedback')
    ]

templates/base.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <link rel="shortcut icon" href="{% static 'tracker/images/finance.ico' %}" type="image/x-icon"/>
    <link href="{% static 'tracker/css/styles.css' %}" rel="stylesheet" />
</head>
<body>
<header class="header">
    <nav class="navigation">
        <a href="{% url 'home' %}"><img src="{% static 'tracker/images/finance.png' %}" alt="Лого" class="corner-icon" ></a>
        <ul class="main-menu">
            {% for item in mainmenu %}
            <li><a href="{% url item.url_name %}">{{ item.title }}</a></li>
            {% endfor %}
        </ul>

    <div class="auth-container">
        <ul class="auth-menu">
            {% if user.is_authenticated %}
            <li><a href="{% url 'users:profile' %}">{{ user.username }}</a> |
                <form method="post" action="{% url 'users:logout' %}" style="display: inline">
                    {% csrf_token %}
                    <button type="submit">
                        Выйти
                    </button>
                </form>
            </li>
            {% else %}
            <li><a href="{% url 'users:register' %}">Регистрация</a> | <a href="{% url 'users:login' %}">Войти</a></li>
        {% endif %}
            </ul>
    </div>
    </nav>
</header>
<div class="container">
    <aside class="sidebar">
        <h3>Категории:</h3>
        {% if categories %}

            <ul>
                {% for cat in categories %}

                <li>{{ cat.name }} <button type="button"><a href="{% url 'update_category' cat.slug %}">Изменить</a></button>
                <button type="button"><a href="{% url 'delete_category' cat.slug %}">Удалить</a></button></li>
                                {% endfor %}
            </ul>
        {% endif %}
    </aside>

    <main>
        {% block content %}
        <button type="button"><a href="{% url 'create_operation' %}">Добавить операцию</a></button>
        <button type="button"><a href="{% url 'create_category' %}">Добавить категорию</a></button>
        {% endblock %}
    </main>
</div>
</body>
</html>